// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJwbcp1seLjuzMNSlfDFmJnRJOQdPZtAY',
    appId: '1:1040266132089:web:146a1cf58e4512ed3c32a8',
    messagingSenderId: '1040266132089',
    projectId: 'messaging-app-1fa8a',
    authDomain: 'messaging-app-1fa8a.firebaseapp.com',
    storageBucket: 'messaging-app-1fa8a.appspot.com',
    measurementId: 'G-XSWXC49ZDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGR36JHObBuMnQZTYDe9rDkaJlCIwnHQ',
    appId: '1:1040266132089:android:bdf903c0504a422e3c32a8',
    messagingSenderId: '1040266132089',
    projectId: 'messaging-app-1fa8a',
    storageBucket: 'messaging-app-1fa8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuwt5k6VCe_UrC9_RJln2nvoqFOjN4Hk',
    appId: '1:1040266132089:ios:32b1a94e0f0d9ac63c32a8',
    messagingSenderId: '1040266132089',
    projectId: 'messaging-app-1fa8a',
    storageBucket: 'messaging-app-1fa8a.appspot.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYuwt5k6VCe_UrC9_RJln2nvoqFOjN4Hk',
    appId: '1:1040266132089:ios:80d71d8abcdcf0653c32a8',
    messagingSenderId: '1040266132089',
    projectId: 'messaging-app-1fa8a',
    storageBucket: 'messaging-app-1fa8a.appspot.com',
    iosBundleId: 'com.example.messageApp.RunnerTests',
  );
}
